config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  root :to => 'welcome#index'

  resources :events do
    put :attending, on: :member
  end

end

app/models/attending_event.rb
class AttendingEvent < ActiveRecord::Base

  belongs_to :event
  belongs_to :user

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user

  has_many :attending_events
  has_many :attendees, through: :attending_events, source: :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include Gravtastic
  gravtastic

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  has_many :events

  has_many :attending_events
  has_many :attending, through: :attending_events, source: :event

  has_attached_file :image,
    :styles => {
      :medium => "300x300>",
      :thumb => "100x100>" },
      :default_url => "/images/:style/Eeyore.jpg"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

         def self.from_omniauth(auth)
           where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
             user.email = auth.info.email
             user.password = Devise.friendly_token[0,20]
             # Need to add name and image to user model in devise first;
             user.name = auth.info.name
            #  user.image = auth.info.image
           end
         end

         def self.new_with_session(params, session)
           super.tap do |user|
             if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
               user.email = data["email"] if user.email.blank?
               user.name = data["name"] if user.name.blank?
              #  user.image = data["image"] if user.image.blank?
              #  user.image = access_token.info.image
             end
           end
         end
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :level << :type << :number << :image
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
    @eventsToday = []
    @eventsTomorrow = []
    @events.each do |event|
      if event.day == Date.today.to_s
        @eventsToday << event
      elsif event.day == (Date.today+1).to_s
        @eventsTomorrow << event
      end
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.save
    redirect_to :controller => 'events', :action => 'index'
  end

  def edit
    @event = Event.find(params[:id])
  end

  def attending
    @event = Event.find(params[:id])
    type = params[:type]
    if type == "attending" && @event.space != 0
      current_user.attending << @event
      @event.space = @event.space - 1
      @event.save
      AdminMailer.new_attending(@event.user, current_user).deliver_now
      redirect_to :back, notice: "You've joined the group. Your number will be sent to #{@event.user.name}"

    else type == "unattending"
      current_user.attending.delete(@event)
      redirect_to :back, notice: "You've removed yourself from the group"
    end
  end



end

def event_params
  params.require(:event).permit(:area, :level, :plan, :meeting, :space, :day)
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update
    # For Rails 4
    account_update_params = devise_parameter_sanitizer.sanitize(:account_update)

    # required for settings form to submit when password is left blank
    if account_update_params[:password].blank?
      puts "entered if statement"
      account_update_params.delete("password")
      account_update_params.delete("password_confirmation")
      puts account_update_params.inspect
    end

    @user = User.find(current_user.id)
    if @user.update_attributes(account_update_params)
      set_flash_message :notice, :updated
      # Sign in the user bypassing validation in case their password changed
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "edit"
    end
  end

  protected

  def after_sign_up_path_for(resource)
    '/users/edit'
  end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
layout "welcome"

  def index
    if user_signed_in?
      redirect_to '/events'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    devise_mapping.to
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/index.html.erb
<div class="st-pusher" id="content">
    <div class="st-content">

      <h1>See who's riding</h1>
      <p>Below you can see who's going riding today and tomorrow. Go to 'Add' if you'd like to tell people you're going up the hill!</p>
        <!-- Tabbable Widget -->
        <div class="tabbable tabs-primary">
        <!-- Tabs -->
          <ul class="nav nav-tabs">
            <li id='tab-today' class="active">
              <a href="#" data-toggle="tab" id="today">Today</a>
            </li>
            <li id='tab-tomorrow'>
              <a href="#" data-toggle="tab" id="tomorrow">Tomorrow</a>
            </li>
          </ul>
          <!-- // END Tabs -->
          <!-- Panes -->
          <div class="tab-content">
            <div id="color-home" class="tab-pane active">
              <div class="st-content-inner">
                <div class="today">
                  <div class="container-fluid">
                    <div class="panel panel-default">
                  </div>
                  <!-- Progress table -->
                  <div class="table-responsive">
                  <table class="table v-middle">
                    <thead>
                      <tr>
                        <th>Name</th>
                        <th>Area</th>
                        <th>Level</th>
                        <th>Plan</th>
                        <th>Meeting</th>
                        <th>Space</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% if @eventsToday.any? %>
                      <% @eventsToday.each do |event| %>
                      <tr>
                        <td>
                          <% if event.user.image? %>
                            <%= image_tag event.user.image.url(:thumb) %>
                          <% else %>
                            <%= image_tag event.user.gravatar_url %>
                          <% end %>
                          <%= event.user.name %>

                        </td>
                        <td><%= event.area %></td>
                        <td><%= event.level %></td>
                        <td><%= event.plan %></td>
                        <td><%= event.meeting.strftime('%H:%M') %></td>
                        <td><%= event.space %></td>
                        <td><% if event.user != current_user && event.space != 0 && user_signed_in? %>
                            <% unless event.attendees.include?(current_user) %>
                          <%= link_to "Join", attending_event_path(event, type: "attending"), class: "btn btn-primary btn-xs", method: :put %>
                          <% end %>
                          <% end %></td>
                      </tr>
                      <% end %>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <div id="color-profile" class="tab-pane">
            <div class="st-content-inner">
              <div class="tomorrow">
                <div class="container-fluid">
                  <div class="panel panel-default">
                  </div>
                  <!-- Progress table -->
                  <div class="table-responsive">
                    <table class="table v-middle">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Area</th>
                          <th>Level</th>
                          <th>Plan</th>
                          <th>Meeting</th>
                          <th>Space</th>
                          <th></th>
                        </tr>
                      </thead>
                      <tbody>
                        <% if @eventsTomorrow.any? %>
                        <% @eventsTomorrow.each do |event| %>
                        <tr>
                          <td>
                            <% unless event.user.nil? %>
                            <%= image_tag event.user.image.url(:thumb) %>
                            <%= event.user.name %>
                            <% end %>
                          </td>
                          <td><%= event.area %></td>
                          <td><%= event.level %></td>
                          <td><%= event.plan %></td>
                          <td><%= event.meeting.strftime('%H:%M') %></td>
                          <td><%= event.space %></td>
                          <td><% if event.user != current_user && event.space != 0 && user_signed_in? %>
                              <% unless event.attendees.include?(current_user) %>
                            <%= link_to "Join", attending_event_path(event, type: "attending"), class: "btn btn-primary btn-xs", method: :put %>
                            <% end %>
                            <% end %></td>
                        </tr>
                        <% end %>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <h2>See what's going on up the mountain right now!</h2>
      <table class="webcam-names">
        <tr>
          <th>Ardent</th>
          <th>Avoriaz</th>
          <th>Morzine</th>
        </tr>
      </table>
      <div class="webcams">
        <iframe id="webcam" type="text/html" frameborder="0" style="height: 500px; max-width: 300px; min-width: 380px;" scrolling="no" src="http://portesdusoleil.livecam360.net/"></iframe>

        <iframe id="webcam" type="text/html" frameborder="0" style="height: 500px; max-width: 300px; min-width: 380px;" scrolling="no" src="http://livecam.avoriaz.com/
        "></iframe>

        <iframe id="webcam" type="text/html" frameborder="0" style="height: 500px; max-width: 300px; min-width: 380px;" scrolling="no" src="http://m.webcam-hd.com/morzine/chamossiere/
        "></iframe>
      </div>
    </div>
  </div>

app/views/events/new.html.erb
<div class="st-pusher" id="content">
<div class="st-content-inner">
  <div class="container-fluid">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for @event, :html => { :class => "form-horizontal" }  do |f| %>
          <div class="form-group">
            <%= f.label :day, "When are you riding?", class: "col-sm-3 control-label" %>
            <div class="col-sm-9">
              <%= f.select :day, options_for_select([['Today', Date.today.to_s],['Tomorrow', (Date.today+1).to_s]]), :data => { :style => "btn-white", :size => "5" } %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :area, "Where are you riding?", class: "col-sm-3 control-label" %>
            <div class="col-sm-9">
              <%= f.text_field :area, class: "form-control", placeholder: "e.g. Pleney" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :level, "Level", class: "col-sm-3 control-label" %>
            <div class="col-sm-9">
                <div class="checkbox">
                <%= f.radio_button :level, "Beginner" %> Beginner (Greens and Blues)
                <br />
                <%= f.radio_button :level, "Intermediate" %> Intermediate (Reds)
                <br />
                <%= f.radio_button :level, "Advanced" %> Advanced (Blacks)
                <br />
                <%= f.radio_button :level, "Nuts" %> Nuts (Anywhere with Snow)
              </div>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :plan, "Plan", class: "col-sm-3 control-label" %>
            <div class="col-sm-9">
                <div class="checkbox">
                <%= f.radio_button :plan, "Piste" %> Piste
                <br />
                <%= f.radio_button :plan, "Park" %> Park
                <br />
                <%= f.radio_button :plan, "Off-Piste" %> Off-Piste
                <br />
                <%= f.radio_button :plan, "All-mountain" %> All-mountain
              </div>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :meeting, "Meet time", class: "col-sm-3 control-label" %>
            <div class="col-sm-9">
              <%= f.time_select :meeting, class: "selectpicker" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :space, "Max group size", class: "col-sm-3 control-label" %>
            <div class="col-sm-9">
              <%= f.select :space, options_for_select([['One', 1],['Two', 2],
              ['Three', 3], ['Four', 4], ['Five', 5], ['Six', 6],
              ['Seven', 7], ['Eight', 8]]),
              :data => { :style => "btn-white", :size => "5" } %>
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-offset-3 col-sm-9">
                <%= f.submit "Submit", class: "btn btn-primary" %>
              </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="st-layout ls-top-navbar ls-bottom-footer show-sidebar sidebar-l2" lang="en">
<head>
  <title>RidingToday</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
</head>
<body>
  <!-- Wrapper required for sidebar transitions -->
      <div class="st-container">

          <!-- Fixed navbar -->
          <div class="navbar navbar-main navbar-default navbar-fixed-top" role="navigation">
              <div class="container-fluid">
                  <div class="navbar-header">
                      <a href="#sidebar-menu" data-effect="st-effect-1" data-toggle="sidebar-menu" class="toggle pull-left visible-xs"><i class="fa fa-bars"></i></a>
                      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
                          <span class="sr-only">Toggle navigation</span>
                      </button>
                      <a href="#sidebar-chat" data-toggle="sidebar-menu" data-effect="st-effect-1" class="toggle pull-right visible-xs"><i class="fa fa-comments"></i></a>
                      <a class="navbar-brand navbar-brand-primary hidden-xs" href="/events">RidingToday</a>
                  </div>
                  <div class="collapse navbar-collapse" id="main-nav">
                      <ul class="nav navbar-nav navbar-user">
                          <!-- User -->
                          <li class='user'>
                            <% if user_signed_in? %>
                              <% if current_user.image? %>
                                <%= image_tag current_user.image.url(:thumb) %>
                              <% else %>
                                <%= image_tag current_user.gravatar_url %>
                              <% end %>
                              <%= link_to "#{current_user.name}", edit_user_registration_path(current_user), class: "name" %>
                            <% end %>
                          </li>
                      </ul>
                      <ul class="nav navbar-nav navbar-right hidden-xs">
                          <li class="pull-right">
                            <div class="container-fluid">
                              <div class="navbar-collapse collapse text-center" id="collapse-buttons">
                                <% if user_signed_in? %>
                                  <%= link_to "Sign out", destroy_user_session_path, class: "btn navbar-btn btn-primary", :method => :delete %>
                                <% end %>
                              </div>
                            </div>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>

          <!-- Sidebar component with st-effect-1 (set on the toggle button within the navbar) -->
          <div class="sidebar left sidebar-size-2 sidebar-offset-0 sidebar-visible-desktop sidebar-visible-mobile sidebar-skin-dark" id="sidebar-menu" data-type="collapse">
              <div class="sidebar-menu">
                  <div data-scrollable>
                      <ul>
                          <li class="category">Navigation</li>
                          <li class="hasSubmenu">
                              <a href="/events"><i class="icon-ship-wheel"></i> <span>Who's riding?</span></a>
                              <ul id="timeline">
                                  <li><a href="/events"><i class="fa fa-circle-o"></i><span>View</span></a>
                                  </li>
                                  <li><a href="/events/new"><i class="fa fa-circle-o"></i><span>Add</span>
                                  </li>
                              </ul>
                          </li>
                          <li>
                            <% if user_signed_in? %>
                              <%= link_to "<i class='icon-user-1'></i>Edit Profile".html_safe, edit_user_registration_path(current_user) %>
                            <% end %>

                          </li>
                          <li class=""><a href="/events"></a>
                          </li>
                          <li class=""><a href="/events"></a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
          <%= yield %>
                  <!-- extra div for emulating position:fixed of the menu -->
                  <div class="st-content-inner">
                      <div class="container-fluid">
                          <div class="footer">RidingToday &copy; Copyright Notice</div>
                      </div>
                  </div>
                  <!-- /st-content-inner -->
                  </div>
              <!-- /st-content -->
              </div>
          <!-- /st-pusher -->
          </div>
      <!-- /st-container -->
  <!-- Inline Script for colors and config objects; used by various external scripts; -->
  <script>
      var colors = {
          "danger-color": "#e74c3c",
          "success-color": "#81b53e",
          "warning-color": "#f0ad4e",
          "inverse-color": "#2c3e50",
          "info-color": "#2d7cb5",
          "default-color": "#6e7882",
          "default-light-color": "#cfd9db",
          "purple-color": "#9D8AC7",
          "mustard-color": "#d4d171",
          "lightred-color": "#e15258",
          "body-bg": "#f6f6f6"
      };
      var config = {
          "theme": "social-1",
          "themes": [],
          "dist": "dist/themes",
          "skins": {
              "docs": {
                  "default": {
                      "primary-color": "#16ae9f"
                  },
                  "orange": {
                      "primary-color": "#e74c3c"
                  },
                  "blue": {
                      "primary-color": "#4687ce"
                  },
                  "purple": {
                      "primary-color": "#af86b9"
                  },
                  "brown": {
                      "primary-color": "#c3a961"
                  }
              },
              "admin": {
                  "default": {
                      "primary-color": "#3498db"
                  },
                  "orange": {
                      "primary-color": "#e74c3c"
                  },
                  "blue": {
                      "primary-color": "#4687ce"
                  },
                  "purple": {
                      "primary-color": "#af86b9"
                  },
                  "brown": {
                      "primary-color": "#c3a961"
                  }
              },
              "layout": {
                  "default": {
                      "primary-color": "#16ae9f"
                  }
              },
              "sidebar": {
                  "default": {
                      "primary-color": "#16ae9f"
                  }
              },
              "navbar": {
                  "default": {
                      "primary-color": "#16ae9f"
                  }
              },
              "color": {
                  "default": {
                      "primary-color": "#16ae9f"
                  }
              },
              "music": {
                  "default": {
                      "primary-color": "#3498db"
                  },
                  "orange": {
                      "primary-color": "#e74c3c"
                  },
                  "blue": {
                      "primary-color": "#4687ce"
                  },
                  "purple": {
                      "primary-color": "#af86b9"
                  },
                  "brown": {
                      "primary-color": "#c3a961"
                  }
              },
              "social-1": {
                  "default": {
                      "primary-color": "#16ae9f"
                  },
                  "orange": {
                      "primary-color": "#e74c3c"
                  },
                  "blue": {
                      "primary-color": "#4687ce"
                  },
                  "purple": {
                      "primary-color": "#af86b9"
                  },
                  "brown": {
                      "primary-color": "#c3a961"
                  }
              },
              "social-2": {
                  "default": {
                      "primary-color": "#16ae9f"
                  },
                  "orange": {
                      "primary-color": "#e74c3c"
                  },
                  "blue": {
                      "primary-color": "#4687ce"
                  },
                  "purple": {
                      "primary-color": "#af86b9"
                  },
                  "brown": {
                      "primary-color": "#c3a961"
                  },
                  "default-nav-inverse": {
                      "color-block": "#242424"
                  }
              },
              "social-3": {
                  "default": {
                      "primary-color": "#16ae9f"
                  },
                  "orange": {
                      "primary-color": "#e74c3c"
                  },
                  "blue": {
                      "primary-color": "#4687ce"
                  },
                  "purple": {
                      "primary-color": "#af86b9"
                  },
                  "brown": {
                      "primary-color": "#c3a961"
                  },
                  "default-nav-inverse": {
                      "color-block": "#242424"
                  }
              },
              "learning": {
                  "default": {
                      "primary-color": "#16ae9f"
                  },
                  "orange": {
                      "primary-color": "#e74c3c"
                  },
                  "blue": {
                      "primary-color": "#4687ce"
                  },
                  "purple": {
                      "primary-color": "#af86b9"
                  },
                  "brown": {
                      "primary-color": "#c3a961"
                  }
              }
          },
          "vendor_css": ["app/icons/pictoicons/css/picto.css", "bower_components/bootstrap3-datepicker/css/datepicker.css", "bower_components/jquery-minicolors/jquery.minicolors.css", "bower_components/seiyria-bootstrap-slider/dist/css/bootstrap-slider.css", "bower_components/highlightjs/styles/railscasts.css", "bower_components/jvectormap/jquery-jvectormap.css", "bower_components/owlcarousel/owl-carousel/owl.carousel.css", "bower_components/morrisjs/morris.css"],
          "discover": {
              "exclude": ["animated-climacons", "bridget", "bootstrap-sass", "bootstrap-rtl", "mocha", "modernizr", "requirejs", "jquery-ui-map", "jquery-ui"]
          },
          "debug": true
      };
  </script>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html class="st-layout ls-top-navbar ls-bottom-footer show-sidebar sidebar-l2" lang="en">
<head>
  <title>RidingToday</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
</head>
<body>



<div class="title">
	<h1><span>RidingToday</span></h1>
</div>
<br />
<div class="welcome">
	<p><span>Join RidingToday to find out who is going to go out today and tomorrow, where they are going to meet,</span></p>
	<p><span>what level they are going to be riding at and what their plans are.</span></p>
</div>

<div class="container clearfix">
  <div class="primary">
    <h2><span>Already a member?</span></h2>
    <% if !user_signed_in? %>
    <h2><span><%= link_to "Sign in", new_user_session_path, class: "btn navbar-btn btn-primary" %></span></h2>
    <h2><span><%= link_to "<i class='fa fa-2x fa-facebook'></i>Sign in with Facebook".html_safe, user_omniauth_authorize_path(:facebook), class: "btn btn-info btn-icon-stacked" %></span></h2>
    <% end %>
 
  </div>
  <div class="secondary">
    <h2><span>Join and go riding today!</span></h2>
    <div class="form">
    
    	
    	    <div class="container-fluid">
    	        <div class="panel panel-default">
    	            <div class="panel-body">
    	            <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
    	              <%= devise_error_messages! %>

    	              <div class="form-group">
    	                <%= f.label :name, "Name", class: "col-sm-3 control-label"  %>
    	                <div class="col-sm-9">
    	                  <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
    	                </div>
    	              </div>
    	              <br />
    	              <div class="form-group">
    	                <%= f.label :email, "Email", class: "col-sm-3 control-label" %>
    	                <div class="col-sm-9">
    	                  <%= f.email_field :email, class: "form-control", autofocus: true, placeholder: "Email" %>
    	                </div>
    	              </div>
    	              <br />
    	              <div class="form-group">
    	                <%= f.label :password, "Password", class: "col-sm-3 control-label" %>
    	                <% if @validatable %>
    	                <em>(<%= @minimum_password_length %> characters minimum)</em>
    	                <% end %>
    	                <div class="col-sm-9">
    	                  <%= f.password_field :password, class: "form-control", autocomplete: "off", placeholder: "At least 8 characters..." %>
    	                </div>
    	              </div>
    	              <br />
    	              <div class="form-group">
    	                <%= f.label :password_confirmation, "Password Confirmation", class: "col-sm-3 control-label" %>
    	                <div class="col-sm-9">
    	                  <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "off" %>
    	                </div>
    	              </div>
    	              <br />
    	              <div class="form-group">
    	                <div class="col-sm-offset-3 col-sm-9">
    	                  <%= f.submit "Sign up", class: "btn btn-primary" %>
    	                </div>
    	              </div>
    	            <% end %>

    	    
    	          </div>
    	    
    	      </div>
    	  
    	  </div>
    	</div>
    </div>
 
  </div>
</div><!-- /.container -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>